/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:metadata
 * Source: Individual metadata.ts files in src/games/ and src/apps/
 */

import type { CategoryId } from "./game-registry";

export interface GameMetadata {
  name: string;
  icon: string;
  color: string;
  description: string;
  category: CategoryId;
  madeByKid: boolean;
  /**
   * The module records gameplay clips (metadata literal clips: true). The
   * generator always writes it; it is optional so a hand-made lookup entry
   * (a test) can leave it out, which means false.
   */
  clips?: boolean;
  /**
   * The orientation the game plays best in on a phone (metadata literal
   * preferredOrientation). GameShell shows the orientation tip from it.
   * Absent for a game that plays well both ways.
   */
  preferredOrientation?: "portrait" | "landscape";
}

export const GAME_METADATA: Record<string, GameMetadata> = {
  "2048": {
    name: "2048",
    icon: "🔢",
    color: "orange",
    description: "Slide and merge numbers",
    category: "arcade",
    madeByKid: false,
    clips: true,
  },
  "arkanoid": {
    name: "Arkanoid",
    icon: "🎱",
    color: "orange",
    description: "Watch balls multiply in this mesmerizing chain reaction game!",
    category: "arcade",
    madeByKid: false,
    clips: true,
  },
  "asteroids": {
    name: "Asteroids",
    icon: "☄️",
    color: "orange",
    description: "Vector space shooter",
    category: "arcade",
    madeByKid: false,
    clips: true,
  },
  "blitz-bomber": {
    name: "Blitz Bomber",
    icon: "✈️",
    color: "cyan",
    description: "Flatten the cartoon city and land your plane",
    category: "action",
    madeByKid: false,
    clips: true,
  },
  "bomberman": {
    name: "Bomberman",
    icon: "💣",
    color: "cyan",
    description: "Grid-based bomb action",
    category: "action",
    madeByKid: false,
    clips: true,
  },
  "breakout": {
    name: "Breakout",
    icon: "🧱",
    color: "orange",
    description: "Brick breaker with power-ups",
    category: "arcade",
    madeByKid: false,
    clips: true,
    preferredOrientation: "portrait",
  },
  "checkers": {
    name: "Checkers",
    icon: "🔴",
    color: "amber",
    description: "Classic checkers game",
    category: "board",
    madeByKid: false,
    clips: true,
  },
  "chess": {
    name: "Chess",
    icon: "♟️",
    color: "amber",
    description: "Classic chess game",
    category: "board",
    madeByKid: false,
    clips: true,
  },
  "cookie-clicker": {
    name: "Cookie Clicker",
    icon: "🍪",
    color: "purple",
    description: "Tap the cookie, buy upgrades",
    category: "puzzle",
    madeByKid: false,
    clips: true,
  },
  "dino-runner": {
    name: "Dino Runner",
    icon: "🦖",
    color: "green",
    description: "Chrome-style endless runner",
    category: "racing",
    madeByKid: false,
    clips: true,
  },
  "endless-runner": {
    name: "Endless Runner",
    icon: "🏃‍♂️",
    color: "cyan",
    description: "Run forever, dodge obstacles",
    category: "action",
    madeByKid: false,
    clips: true,
    preferredOrientation: "landscape",
  },
  "flappy-bird": {
    name: "Flappy Bird",
    icon: "🐦",
    color: "orange",
    description: "Tap to fly through pipes",
    category: "arcade",
    madeByKid: false,
    clips: true,
    preferredOrientation: "portrait",
  },
  "four-wheeler-3d": {
    name: "Four-Wheeler Adventure 3D",
    icon: "🏍️",
    color: "green",
    description: "Ride, hunt, fish, fly and build inside a big 3D world",
    category: "racing",
    madeByKid: true,
    clips: true,
  },
  "four-wheeler-adventure": {
    name: "Four-Wheeler Adventure",
    icon: "🐕",
    color: "green",
    description: "Ride, hunt, fish & race in a huge open world",
    category: "racing",
    madeByKid: true,
    clips: true,
  },
  "hextris": {
    name: "Hextris",
    icon: "⬡",
    color: "purple",
    description: "Hexagon color matching",
    category: "puzzle",
    madeByKid: false,
    clips: true,
  },
  "hill-climb": {
    name: "Hill Climb",
    icon: "🏔️",
    color: "green",
    description: "Physics-based hill climbing",
    category: "racing",
    madeByKid: false,
    clips: true,
  },
  "math-attack": {
    name: "Math Attack",
    icon: "🔢",
    color: "orange",
    description: "Solve math problems before they hit the ground",
    category: "arcade",
    madeByKid: false,
    clips: true,
  },
  "memory-match": {
    name: "Memory Match",
    icon: "🧠",
    color: "purple",
    description: "Match the cards",
    category: "puzzle",
    madeByKid: false,
    clips: true,
  },
  "monster-truck": {
    name: "Monster Truck",
    icon: "🚗",
    color: "green",
    description: "3D monster truck open world",
    category: "racing",
    madeByKid: false,
    clips: true,
  },
  "oregon-trail": {
    name: "Oregon Trail",
    icon: "🤠",
    color: "violet",
    description: "Classic pioneer adventure",
    category: "retro",
    madeByKid: false,
    clips: true,
  },
  "platformer": {
    name: "Platformer",
    icon: "🏃",
    color: "cyan",
    description: "Jump and run adventure",
    category: "action",
    madeByKid: false,
    clips: true,
    preferredOrientation: "landscape",
  },
  "quoridor": {
    name: "Quoridor",
    icon: "🧱",
    color: "amber",
    description: "Strategic wall-placing game",
    category: "board",
    madeByKid: false,
    clips: true,
  },
  "retro-arcade": {
    name: "Retro Arcade",
    icon: "🕹️",
    color: "violet",
    description: "Classic console emulator",
    category: "retro",
    madeByKid: false,
    clips: true,
  },
  "snake": {
    name: "Snake",
    icon: "🐍",
    color: "orange",
    description: "Classic snake game",
    category: "arcade",
    madeByKid: false,
    clips: true,
  },
  "space-invaders": {
    name: "Space Invaders",
    icon: "👾",
    color: "orange",
    description: "Classic alien shooter",
    category: "arcade",
    madeByKid: false,
    clips: true,
  },
  "wordle": {
    name: "Wordle",
    icon: "📝",
    color: "purple",
    description: "Guess the word with age-appropriate difficulty",
    category: "puzzle",
    madeByKid: false,
    clips: true,
  },
  "drawing-app": {
    name: "Drawing",
    icon: "🎨",
    color: "pink",
    description: "Draw and create art",
    category: "apps",
    madeByKid: false,
    clips: false,
  },
  "drum-machine": {
    name: "Drum Machine",
    icon: "🥁",
    color: "pink",
    description: "Make beats and loops",
    category: "apps",
    madeByKid: false,
    clips: false,
  },
  "joke-generator": {
    name: "Jokes",
    icon: "😂",
    color: "pink",
    description: "Funny jokes for kids",
    category: "apps",
    madeByKid: false,
    clips: false,
  },
  "toy-finder": {
    name: "Toy Finder",
    icon: "🧸",
    color: "pink",
    description: "Find cool toys",
    category: "apps",
    madeByKid: false,
    clips: false,
  },
  "trivia": {
    name: "Trivia Quiz",
    icon: "🧠",
    color: "pink",
    description: "Test your knowledge with age-appropriate trivia questions",
    category: "apps",
    madeByKid: false,
    clips: false,
  },
  "virtual-pet": {
    name: "Virtual Pet",
    icon: "🐣",
    color: "pink",
    description: "Raise your digital pet",
    category: "apps",
    madeByKid: false,
    clips: false,
  },
  "weather": {
    name: "Weather",
    icon: "🌤️",
    color: "pink",
    description: "Check the weather",
    category: "apps",
    madeByKid: false,
    clips: false,
  },
};

/**
 * Get metadata for a game by its appId.
 * Returns a default if game not found.
 */
export function getGameMetadata(appId: string): GameMetadata {
  // Object.hasOwn: appId can be attacker-choosable (achievement ids embed
  // it), and an inherited key like "constructor" is truthy — the plain
  // GAME_METADATA[appId] lookup would skip the fallback and render junk.
  return (
    (Object.hasOwn(GAME_METADATA, appId) ? GAME_METADATA[appId] : undefined) || {
      name: appId,
      icon: "🎮",
      color: "gray",
      description: "A game",
      category: "arcade" as CategoryId,
      madeByKid: false,
      clips: false,
    }
  );
}

/**
 * Static card color map - Tailwind can't analyze dynamic classes.
 * One solid 700 shade per color: white text on every one of them measures
 * at least 4.5:1. (A gradient from 500 to 700 failed at the light end, and
 * a gradient on every card is decoration nobody chose.)
 */
const SURFACE_MAP: Record<string, string> = {
  green: "bg-green-700",
  red: "bg-red-700",
  amber: "bg-amber-700",
  slate: "bg-slate-700",
  emerald: "bg-emerald-700",
  sky: "bg-sky-700",
  orange: "bg-orange-700",
  lime: "bg-lime-700",
  purple: "bg-purple-700",
  yellow: "bg-yellow-700",
  cyan: "bg-cyan-700",
  blue: "bg-blue-700",
  pink: "bg-pink-700",
  stone: "bg-stone-700",
  indigo: "bg-indigo-700",
  violet: "bg-violet-700",
  gray: "bg-gray-700",
};

/**
 * Get the Tailwind background class of a game's card (one solid color).
 */
export function getGameSurface(appId: string): string {
  const { color } = getGameMetadata(appId);
  return SURFACE_MAP[color] || SURFACE_MAP.gray;
}
