import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

import {
  AUDIO_BUS_LINT_FILES,
  AUDIO_BUS_RESTRICTED_SYNTAX,
  AUDIO_BUS_TEST_IGNORES,
  LEGACY_AUDIO_SITE_PATHS,
} from "./src/shared/lib/audio/audioBusRule.mjs";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Game sound goes through the shared game-audio bus (getGameAudio() in
    // src/shared/lib/audio), so clips can hear it and the game's sound
    // switch can mute it. This bans new AudioContext, x.AudioContext,
    // webkitAudioContext, .destination, new Audio(), <audio>, and three.js
    // or drei audio in every game and app. See design/ARCHITECTURE.md,
    // section "Audio".
    name: "hanks-hits/game-audio-bus",
    files: [...AUDIO_BUS_LINT_FILES],
    ignores: [
      ...AUDIO_BUS_TEST_IGNORES,
      // LEGACY ignore list: the files that break this rule today. Each
      // migration PR removes its own files from LEGACY_AUDIO_SITES (in
      // src/shared/lib/audio/audioBusRule.mjs). Never add a file to it. The
      // source-scan test shares the same list: it fails on a stale entry,
      // and on a listed file that gets more bypasses than its ceiling.
      ...LEGACY_AUDIO_SITE_PATHS,
    ],
    rules: {
      "no-restricted-syntax": ["error", ...AUDIO_BUS_RESTRICTED_SYNTAX],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    // Generated by scripts/clips/aac-wasm (Emscripten output, checked by its SHA-256).
    "public/clips/aac/**",
  ]),
]);

export default eslintConfig;
