/**
 * The logic of the game metadata generator (generate-game-metadata.ts), with
 * no side effects, so tests can run it.
 *
 * It reads each src/games/<name>/metadata.ts and src/apps/<name>/metadata.ts
 * with the same plain-literal reader as the runtime home-page scan
 * (src/shared/lib/metadataLiterals.ts), and writes the static lookup
 * src/shared/lib/gameMetadata.generated.ts.
 */

import * as fs from "fs";
import * as path from "path";
import { readMetadataLiterals } from "../src/shared/lib/metadataLiterals";

export interface ParsedMetadata {
  id: string;
  name: string;
  emoji: string;
  category: string;
  description?: string;
  madeByKid: boolean;
  clips: boolean;
}

/** Reads one metadata.ts text. Null when a required field (name, emoji, category) is missing. */
export function parseMetadataContent(content: string, dirName: string): ParsedMetadata | null {
  const fields = readMetadataLiterals(content);
  if (!fields.name || !fields.emoji || !fields.category) return null;
  return {
    // Same id fallback as the runtime scan (game-registry parseMetadata),
    // so a missing explicit id can't make home and profile disagree on
    // whether a game exists.
    id: fields.id ?? dirName,
    name: fields.name,
    emoji: fields.emoji,
    category: fields.category,
    description: fields.description,
    madeByKid: fields.madeByKid ?? false,
    clips: fields.clips ?? false,
  };
}

/** Every module with a readable metadata.ts under srcDir/<type>, in directory order. */
export function scanMetadata(srcDir: string, type: "games" | "apps"): ParsedMetadata[] {
  const items: ParsedMetadata[] = [];
  const dir = path.join(srcDir, type);
  if (!fs.existsSync(dir)) {
    console.warn(`Directory not found: ${dir}`);
    return items;
  }
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const metadataPath = path.join(dir, entry.name, "metadata.ts");
    if (!fs.existsSync(metadataPath)) continue;
    try {
      const metadata = parseMetadataContent(fs.readFileSync(metadataPath, "utf-8"), entry.name);
      if (metadata) items.push(metadata);
      else console.warn(`Missing required fields in ${metadataPath}`);
    } catch (err) {
      console.error(`Error parsing ${metadataPath}:`, err);
    }
  }
  return items;
}

// Color mapping based on category (keeping existing pattern)
const CATEGORY_COLORS: Record<string, string> = {
  racing: "green",
  board: "amber",
  arcade: "orange",
  action: "cyan",
  puzzle: "purple",
  retro: "violet",
  apps: "pink",
};

/** The text of gameMetadata.generated.ts for these modules. */
export function generateOutput(items: ParsedMetadata[]): string {
  const entries = items
    .map((item) => {
      const color = CATEGORY_COLORS[item.category] || "gray";
      return `  "${item.id}": {
    name: "${item.name}",
    icon: "${item.emoji}",
    color: "${color}",
    description: "${item.description || ""}",
    category: "${item.category}",
    madeByKid: ${item.madeByKid},
    clips: ${item.clips},
  }`;
    })
    .join(",\n");

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:metadata
 * Source: Individual metadata.ts files in src/games/ and src/apps/
 */

import type { CategoryId } from "./game-registry";

export interface GameMetadata {
  name: string;
  icon: string;
  color: string;
  description: string;
  category: CategoryId;
  madeByKid: boolean;
  /**
   * The module records gameplay clips (metadata literal clips: true). The
   * generator always writes it; it is optional so a hand-made lookup entry
   * (a test) can leave it out, which means false.
   */
  clips?: boolean;
}

export const GAME_METADATA: Record<string, GameMetadata> = {
${entries},
};

/**
 * Get metadata for a game by its appId.
 * Returns a default if game not found.
 */
export function getGameMetadata(appId: string): GameMetadata {
  // Object.hasOwn: appId can be attacker-choosable (achievement ids embed
  // it), and an inherited key like "constructor" is truthy — the plain
  // GAME_METADATA[appId] lookup would skip the fallback and render junk.
  return (
    (Object.hasOwn(GAME_METADATA, appId) ? GAME_METADATA[appId] : undefined) || {
      name: appId,
      icon: "🎮",
      color: "gray",
      description: "A game",
      category: "arcade" as CategoryId,
      madeByKid: false,
      clips: false,
    }
  );
}

/**
 * Static gradient class map - Tailwind can't analyze dynamic classes.
 */
const GRADIENT_MAP: Record<string, string> = {
  green: "from-green-500 to-green-700",
  red: "from-red-500 to-red-700",
  amber: "from-amber-500 to-amber-700",
  slate: "from-slate-500 to-slate-700",
  emerald: "from-emerald-500 to-emerald-700",
  sky: "from-sky-500 to-sky-700",
  orange: "from-orange-500 to-orange-700",
  lime: "from-lime-500 to-lime-700",
  purple: "from-purple-500 to-purple-700",
  yellow: "from-yellow-500 to-yellow-700",
  cyan: "from-cyan-500 to-cyan-700",
  blue: "from-blue-500 to-blue-700",
  pink: "from-pink-500 to-pink-700",
  stone: "from-stone-500 to-stone-700",
  indigo: "from-indigo-500 to-indigo-700",
  violet: "from-violet-500 to-violet-700",
  gray: "from-gray-500 to-gray-700",
};

/**
 * Get Tailwind background gradient classes for a game.
 */
export function getGameGradient(appId: string): string {
  const { color } = getGameMetadata(appId);
  return GRADIENT_MAP[color] || GRADIENT_MAP.gray;
}
`;
}
