/**
 * The logic of the game metadata generator (generate-game-metadata.ts), with
 * no side effects, so tests can run it.
 *
 * It reads each src/games/<name>/metadata.ts and src/apps/<name>/metadata.ts
 * with the same plain-literal reader as the runtime home-page scan
 * (src/shared/lib/metadataLiterals.ts), and writes the static lookup
 * src/shared/lib/gameMetadata.generated.ts.
 */

import * as fs from "fs";
import * as path from "path";
import { readMetadataLiterals } from "../src/shared/lib/metadataLiterals";

export interface ParsedMetadata {
  id: string;
  name: string;
  emoji: string;
  category: string;
  description?: string;
  madeByKid: boolean;
  clips: boolean;
}

/** Reads one metadata.ts text. Null when a required field (name, emoji, category) is missing. */
export function parseMetadataContent(content: string, dirName: string): ParsedMetadata | null {
  const fields = readMetadataLiterals(content);
  if (!fields.name || !fields.emoji || !fields.category) return null;
  return {
    // Same id fallback as the runtime scan (game-registry parseMetadata),
    // so a missing explicit id can't make home and profile disagree on
    // whether a game exists.
    id: fields.id ?? dirName,
    name: fields.name,
    emoji: fields.emoji,
    category: fields.category,
    description: fields.description,
    madeByKid: fields.madeByKid ?? false,
    clips: fields.clips ?? false,
  };
}

/** Every module with a readable metadata.ts under srcDir/<type>, in directory order. */
export function scanMetadata(srcDir: string, type: "games" | "apps"): ParsedMetadata[] {
  const items: ParsedMetadata[] = [];
  const dir = path.join(srcDir, type);
  if (!fs.existsSync(dir)) {
    console.warn(`Directory not found: ${dir}`);
    return items;
  }
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const metadataPath = path.join(dir, entry.name, "metadata.ts");
    if (!fs.existsSync(metadataPath)) continue;
    try {
      const metadata = parseMetadataContent(fs.readFileSync(metadataPath, "utf-8"), entry.name);
      if (metadata) items.push(metadata);
      else console.warn(`Missing required fields in ${metadataPath}`);
    } catch (err) {
      console.error(`Error parsing ${metadataPath}:`, err);
    }
  }
  return items;
}

// Color mapping based on category (keeping existing pattern)
const CATEGORY_COLORS: Record<string, string> = {
  racing: "green",
  board: "amber",
  arcade: "orange",
  action: "cyan",
  puzzle: "purple",
  retro: "violet",
  apps: "pink",
};

/** The text of gameMetadata.generated.ts for these modules. */
export function generateOutput(items: ParsedMetadata[]): string {
  const entries = items
    .map((item) => {
      const color = CATEGORY_COLORS[item.category] || "gray";
      return `  "${item.id}": {
    name: "${item.name}",
    icon: "${item.emoji}",
    color: "${color}",
    description: "${item.description || ""}",
    category: "${item.category}",
    madeByKid: ${item.madeByKid},
    clips: ${item.clips},
  }`;
    })
    .join(",\n");

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:metadata
 * Source: Individual metadata.ts files in src/games/ and src/apps/
 */

import type { CategoryId } from "./game-registry";

export interface GameMetadata {
  name: string;
  icon: string;
  color: string;
  description: string;
  category: CategoryId;
  madeByKid: boolean;
  /**
   * The module records gameplay clips (metadata literal clips: true). The
   * generator always writes it; it is optional so a hand-made lookup entry
   * (a test) can leave it out, which means false.
   */
  clips?: boolean;
}

export const GAME_METADATA: Record<string, GameMetadata> = {
${entries},
};

/**
 * Get metadata for a game by its appId.
 * Returns a default if game not found.
 */
export function getGameMetadata(appId: string): GameMetadata {
  // Object.hasOwn: appId can be attacker-choosable (achievement ids embed
  // it), and an inherited key like "constructor" is truthy — the plain
  // GAME_METADATA[appId] lookup would skip the fallback and render junk.
  return (
    (Object.hasOwn(GAME_METADATA, appId) ? GAME_METADATA[appId] : undefined) || {
      name: appId,
      icon: "🎮",
      color: "gray",
      description: "A game",
      category: "arcade" as CategoryId,
      madeByKid: false,
      clips: false,
    }
  );
}

/**
 * Static card color map - Tailwind can't analyze dynamic classes.
 * One solid 700 shade per color: white text on every one of them measures
 * at least 4.5:1. (A gradient from 500 to 700 failed at the light end, and
 * a gradient on every card is decoration nobody chose.)
 */
const SURFACE_MAP: Record<string, string> = {
  green: "bg-green-700",
  red: "bg-red-700",
  amber: "bg-amber-700",
  slate: "bg-slate-700",
  emerald: "bg-emerald-700",
  sky: "bg-sky-700",
  orange: "bg-orange-700",
  lime: "bg-lime-700",
  purple: "bg-purple-700",
  yellow: "bg-yellow-700",
  cyan: "bg-cyan-700",
  blue: "bg-blue-700",
  pink: "bg-pink-700",
  stone: "bg-stone-700",
  indigo: "bg-indigo-700",
  violet: "bg-violet-700",
  gray: "bg-gray-700",
};

/**
 * Get the Tailwind background class of a game's card (one solid color).
 */
export function getGameSurface(appId: string): string {
  const { color } = getGameMetadata(appId);
  return SURFACE_MAP[color] || SURFACE_MAP.gray;
}
`;
}
