/**
 * Generates gameMetadata.ts from the individual metadata.ts files in games/ and apps/.
 * Run with: pnpm generate:metadata (or npx tsx scripts/generate-game-metadata.ts)
 */

import * as fs from "fs";
import * as path from "path";

const SRC_DIR = path.join(__dirname, "..", "src");
const OUTPUT_FILE = path.join(SRC_DIR, "shared", "lib", "gameMetadata.generated.ts");

interface ParsedMetadata {
  id: string;
  name: string;
  emoji: string;
  category: string;
  description?: string;
  madeByKid: boolean;
}

function parseMetadataFile(
  filePath: string,
  dirName: string
): ParsedMetadata | null {
  try {
    const content = fs.readFileSync(filePath, "utf-8");

    const idMatch = content.match(/id:\s*["']([^"']+)["']/);
    const nameMatch = content.match(/name:\s*["']([^"']+)["']/);
    const emojiMatch = content.match(/emoji:\s*["']([^"']+)["']/);
    const categoryMatch = content.match(/category:\s*["']([^"']+)["']/);
    const descMatch = content.match(/description:\s*["']([^"']+)["']/);
    const madeByKidMatch = content.match(/madeByKid:\s*(true|false)/);

    if (!nameMatch || !emojiMatch || !categoryMatch) {
      console.warn(`Missing required fields in ${filePath}`);
      return null;
    }

    return {
      // Same id fallback as the runtime scan (game-registry parseMetadata),
      // so a missing explicit id can't make home and profile disagree on
      // whether a game exists.
      id: idMatch ? idMatch[1] : dirName,
      name: nameMatch[1],
      emoji: emojiMatch[1],
      category: categoryMatch[1],
      description: descMatch?.[1],
      madeByKid: madeByKidMatch ? madeByKidMatch[1] === "true" : false,
    };
  } catch (err) {
    console.error(`Error parsing ${filePath}:`, err);
    return null;
  }
}

function scanDirectory(type: "games" | "apps"): ParsedMetadata[] {
  const items: ParsedMetadata[] = [];
  const dir = path.join(SRC_DIR, type);

  if (!fs.existsSync(dir)) {
    console.warn(`Directory not found: ${dir}`);
    return items;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const metadataPath = path.join(dir, entry.name, "metadata.ts");
    if (fs.existsSync(metadataPath)) {
      const metadata = parseMetadataFile(metadataPath, entry.name);
      if (metadata) {
        items.push(metadata);
      }
    }
  }

  return items;
}

// Color mapping based on category (keeping existing pattern)
const CATEGORY_COLORS: Record<string, string> = {
  racing: "green",
  board: "amber",
  arcade: "orange",
  action: "cyan",
  puzzle: "purple",
  retro: "violet",
  apps: "pink",
};

function generateOutput(items: ParsedMetadata[]): string {
  const entries = items
    .map((item) => {
      const color = CATEGORY_COLORS[item.category] || "gray";
      return `  "${item.id}": {
    name: "${item.name}",
    icon: "${item.emoji}",
    color: "${color}",
    description: "${item.description || ""}",
    category: "${item.category}",
    madeByKid: ${item.madeByKid},
  }`;
    })
    .join(",\n");

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:metadata
 * Source: Individual metadata.ts files in src/games/ and src/apps/
 */

import type { CategoryId } from "./game-registry";

export interface GameMetadata {
  name: string;
  icon: string;
  color: string;
  description: string;
  category: CategoryId;
  madeByKid: boolean;
}

export const GAME_METADATA: Record<string, GameMetadata> = {
${entries},
};

/**
 * Get metadata for a game by its appId.
 * Returns a default if game not found.
 */
export function getGameMetadata(appId: string): GameMetadata {
  // Object.hasOwn: appId can be attacker-choosable (achievement ids embed
  // it), and an inherited key like "constructor" is truthy — the plain
  // GAME_METADATA[appId] lookup would skip the fallback and render junk.
  return (
    (Object.hasOwn(GAME_METADATA, appId) ? GAME_METADATA[appId] : undefined) || {
      name: appId,
      icon: "🎮",
      color: "gray",
      description: "A game",
      category: "arcade" as CategoryId,
      madeByKid: false,
    }
  );
}

/**
 * Static card color map - Tailwind can't analyze dynamic classes.
 * One solid 700 shade per color: white text on every one of them measures
 * at least 4.5:1. (A gradient from 500 to 700 failed at the light end, and
 * a gradient on every card is decoration nobody chose.)
 */
const SURFACE_MAP: Record<string, string> = {
  green: "bg-green-700",
  red: "bg-red-700",
  amber: "bg-amber-700",
  slate: "bg-slate-700",
  emerald: "bg-emerald-700",
  sky: "bg-sky-700",
  orange: "bg-orange-700",
  lime: "bg-lime-700",
  purple: "bg-purple-700",
  yellow: "bg-yellow-700",
  cyan: "bg-cyan-700",
  blue: "bg-blue-700",
  pink: "bg-pink-700",
  stone: "bg-stone-700",
  indigo: "bg-indigo-700",
  violet: "bg-violet-700",
  gray: "bg-gray-700",
};

/**
 * Get the Tailwind background class of a game's card (one solid color).
 */
export function getGameSurface(appId: string): string {
  const { color } = getGameMetadata(appId);
  return SURFACE_MAP[color] || SURFACE_MAP.gray;
}
`;
}

// Main
const games = scanDirectory("games");
const apps = scanDirectory("apps");
const allItems = [...games, ...apps];

console.log(`Found ${games.length} games and ${apps.length} apps`);

const output = generateOutput(allItems);
fs.writeFileSync(OUTPUT_FILE, output);

console.log(`Generated ${OUTPUT_FILE}`);
