// Auto-generated SNES game catalog
// DO NOT EDIT - regenerate using scripts/upload_snes_roms.py

export type GameGenre =
  | "rpg"
  | "platformer"
  | "action"
  | "fighting"
  | "adventure"
  | "racing"
  | "puzzle"
  | "sports"
  | "shooter"
  | "strategy";

export interface CatalogGame {
  id: string;
  displayName: string;
  filename: string;
  genre: GameGenre;
  favorite: boolean;
}

// ROM base URL - env var can override, but the default is the same-origin
// /api/roms proxy (which works in every environment; a bare "/roms" fallback
// used to 404 all of local dev because nothing serves that path)
export const ROM_BASE_URL =
  process.env.NEXT_PUBLIC_ROM_CDN_URL || "/api/roms";

export function getRomUrl(game: CatalogGame): string {
  return `${ROM_BASE_URL}/snes/${game.filename}`;
}

export function searchSnesGames(query: string): CatalogGame[] {
  const q = query.toLowerCase().trim();
  if (!q) return SNES_CATALOG;
  return SNES_CATALOG.filter((g) =>
    g.displayName.toLowerCase().includes(q)
  );
}

export function getSnesGamesByGenre(genre: GameGenre): CatalogGame[] {
  return SNES_CATALOG.filter((g) => g.genre === genre);
}

export function getFeaturedGames(): CatalogGame[] {
  return SNES_CATALOG.filter((g) => g.favorite);
}

export const SNES_CATALOG: CatalogGame[] = [
  {
    id: "snes-7th-saga",
    displayName: "7th Saga",
    filename: "7th_saga.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-act-raiser-1",
    displayName: "Act Raiser 1",
    filename: "act_raiser_1.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-act-raiser-2",
    displayName: "Act Raiser 2",
    filename: "act_raiser_2.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-aladdin",
    displayName: "Aladdin",
    filename: "aladdin.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-alien-3",
    displayName: "Alien 3",
    filename: "alien_3.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-alien-vs-predator",
    displayName: "Alien vs. Predator",
    filename: "alien_vs_predator.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-another-world",
    displayName: "Another World",
    filename: "another_world.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-arcana",
    displayName: "Arcana",
    filename: "arcana.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-axelay",
    displayName: "Axelay",
    filename: "axelay.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-bahamut-lagoon",
    displayName: "Bahamut Lagoon",
    filename: "bahamut_lagoon.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-barts-nightmare",
    displayName: "Bart's Nightmare",
    filename: "barts_nightmare.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-battletoads-and-double-dragon-the-ultimate-team",
    displayName: "Battletoads & Double Dragon - The Ultimate Team",
    filename: "battletoads_and_double_dragon_the_ultimate_team.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-battletoads-in-battlemaniacs",
    displayName: "Battletoads in Battlemaniacs",
    filename: "battletoads_in_battlemaniacs.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-boogerman",
    displayName: "Boogerman",
    filename: "boogerman.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-brain-lord",
    displayName: "Brain Lord",
    filename: "brain_lord.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-breath-of-fire-1",
    displayName: "Breath of Fire 1",
    filename: "breath_of_fire_1.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-breath-of-fire-2",
    displayName: "Breath of Fire 2",
    filename: "breath_of_fire_2.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-cannon-fodder",
    displayName: "Cannon Fodder",
    filename: "cannon_fodder.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-castlevania-dracula-x",
    displayName: "Castlevania - Dracula X",
    filename: "castlevania_dracula_x.smc",
    genre: "action",
    favorite: true,
  },
  {
    id: "snes-chronotrigger",
    displayName: "ChronoTrigger",
    filename: "chronotrigger.smc",
    genre: "rpg",
    favorite: true,
  },
  {
    id: "snes-civilization",
    displayName: "Civilization",
    filename: "civilization.smc",
    genre: "strategy",
    favorite: false,
  },
  {
    id: "snes-contra-iii-the-alien-wars",
    displayName: "Contra III - The Alien Wars",
    filename: "contra_iii_the_alien_wars.smc",
    genre: "action",
    favorite: true,
  },
  {
    id: "snes-cybernator",
    displayName: "Cybernator",
    filename: "cybernator.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-demons-crest",
    displayName: "Demon's Crest",
    filename: "demons_crest.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-desert-strike-return-to-the-gulf",
    displayName: "Desert Strike - Return to the Gulf",
    filename: "desert_strike_return_to_the_gulf.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-donald-duck-maui-mallard-in-cold-shadow",
    displayName: "Donald Duck - Maui Mallard in Cold Shadow",
    filename: "donald_duck_maui_mallard_in_cold_shadow.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-donkey-kong-1-country",
    displayName: "Donkey Kong 1 - Country",
    filename: "donkey_kong_1_country.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-donkey-kong-2-diddy-kongs-quest",
    displayName: "Donkey Kong 2 - Diddy Kong's Quest",
    filename: "donkey_kong_2_diddy_kongs_quest.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-donkey-kong-3-dixie-kongs-double-trouble",
    displayName: "Donkey Kong 3 - Dixie Kong's Double Trouble",
    filename: "donkey_kong_3_dixie_kongs_double_trouble.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-doom",
    displayName: "Doom",
    filename: "doom.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-drakkhen",
    displayName: "Drakkhen",
    filename: "drakkhen.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-evo-search-for-eden",
    displayName: "E.V.O. Search for Eden",
    filename: "evo_search_for_eden.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-earthbound",
    displayName: "Earthbound",
    filename: "earthbound.smc",
    genre: "rpg",
    favorite: true,
  },
  {
    id: "snes-earthworm-jim-1",
    displayName: "Earthworm Jim 1",
    filename: "earthworm_jim_1.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-earthworm-jim-2",
    displayName: "Earthworm Jim 2",
    filename: "earthworm_jim_2.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-f-zero",
    displayName: "F-Zero",
    filename: "f_zero.smc",
    genre: "racing",
    favorite: true,
  },
  {
    id: "snes-fatal-fury-1",
    displayName: "Fatal Fury 1",
    filename: "fatal_fury_1.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-fatal-fury-2",
    displayName: "Fatal Fury 2",
    filename: "fatal_fury_2.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-final-fantasy-mystic-quest",
    displayName: "Final Fantasy - Mystic Quest",
    filename: "final_fantasy_mystic_quest.smc",
    genre: "rpg",
    favorite: true,
  },
  {
    id: "snes-final-fantasy-2",
    displayName: "Final Fantasy 2",
    filename: "final_fantasy_2.smc",
    genre: "rpg",
    favorite: true,
  },
  {
    id: "snes-final-fantasy-3",
    displayName: "Final Fantasy 3",
    filename: "final_fantasy_3.smc",
    genre: "rpg",
    favorite: true,
  },
  {
    id: "snes-final-fantasy-v",
    displayName: "Final Fantasy V",
    filename: "final_fantasy_v.smc",
    genre: "rpg",
    favorite: true,
  },
  {
    id: "snes-final-fight-1",
    displayName: "Final Fight 1",
    filename: "final_fight_1.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-final-fight-2",
    displayName: "Final Fight 2",
    filename: "final_fight_2.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-final-fight-3",
    displayName: "Final Fight 3",
    filename: "final_fight_3.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-first-samurai",
    displayName: "First Samurai",
    filename: "first_samurai.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-flashback",
    displayName: "Flashback",
    filename: "flashback.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-front-mission",
    displayName: "Front Mission",
    filename: "front_mission.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-front-mission-gun-hazard",
    displayName: "Front Mission - Gun Hazard",
    filename: "front_mission_gun_hazard.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-genghis-khan-ii-clan-of-the-gray-wolf",
    displayName: "Genghis Khan II - Clan of the Gray Wolf",
    filename: "genghis_khan_ii_clan_of_the_gray_wolf.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-gradius-iii",
    displayName: "Gradius III",
    filename: "gradius_iii.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-gundam-wing-endless-duel",
    displayName: "Gundam Wing - Endless Duel",
    filename: "gundam_wing_endless_duel.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-harvest-moon",
    displayName: "Harvest Moon",
    filename: "harvest_moon.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-illusion-of-gaia",
    displayName: "Illusion of Gaia",
    filename: "illusion_of_gaia.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-jaki-crush",
    displayName: "Jaki Crush",
    filename: "jaki_crush.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-killer-instinct",
    displayName: "Killer Instinct",
    filename: "killer_instinct.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-kirby-superstar",
    displayName: "Kirby Superstar",
    filename: "kirby_superstar.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-kirbys-avalanche",
    displayName: "Kirby's Avalanche",
    filename: "kirbys_avalanche.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-kirbys-dream-course",
    displayName: "Kirby's Dream Course",
    filename: "kirbys_dream_course.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-kirbys-dreamland-3",
    displayName: "Kirby's Dreamland 3",
    filename: "kirbys_dreamland_3.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-knights-of-the-round",
    displayName: "Knights of the Round",
    filename: "knights_of_the_round.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-lemmings-1",
    displayName: "Lemmings 1",
    filename: "lemmings_1.smc",
    genre: "puzzle",
    favorite: false,
  },
  {
    id: "snes-lemmings-2-the-tribes",
    displayName: "Lemmings 2 - The Tribes",
    filename: "lemmings_2_the_tribes.smc",
    genre: "puzzle",
    favorite: false,
  },
  {
    id: "snes-lufia-1-the-fortress-of-doom",
    displayName: "Lufia 1 - The Fortress of Doom",
    filename: "lufia_1_the_fortress_of_doom.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-lufia-2-rise-of-the-sinistrals",
    displayName: "Lufia 2 - Rise of the Sinistrals",
    filename: "lufia_2_rise_of_the_sinistrals.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-mario-is-missing",
    displayName: "Mario is Missing",
    filename: "mario_is_missing.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-mega-man-7",
    displayName: "Mega Man 7",
    filename: "mega_man_7.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-mega-man-x-1",
    displayName: "Mega Man X 1",
    filename: "mega_man_x_1.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-mega-man-x-2",
    displayName: "Mega Man X 2",
    filename: "mega_man_x_2.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-mega-man-x-3",
    displayName: "Mega Man X 3",
    filename: "mega_man_x_3.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-metal-marines",
    displayName: "Metal Marines",
    filename: "metal_marines.smc",
    genre: "strategy",
    favorite: false,
  },
  {
    id: "snes-metal-warriors",
    displayName: "Metal Warriors",
    filename: "metal_warriors.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-mortal-kombat-1",
    displayName: "Mortal Kombat 1",
    filename: "mortal_kombat_1.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-mortal-kombat-2",
    displayName: "Mortal Kombat 2",
    filename: "mortal_kombat_2.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-mortal-kombat-3",
    displayName: "Mortal Kombat 3",
    filename: "mortal_kombat_3.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-mystical-ninja",
    displayName: "Mystical Ninja",
    filename: "mystical_ninja.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-nba-jam",
    displayName: "NBA Jam",
    filename: "nba_jam.smc",
    genre: "sports",
    favorite: false,
  },
  {
    id: "snes-nba-jam-tournament-edition",
    displayName: "NBA Jam Tournament Edition",
    filename: "nba_jam_tournament_edition.smc",
    genre: "sports",
    favorite: false,
  },
  {
    id: "snes-obitus",
    displayName: "Obitus",
    filename: "obitus.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-ogre-battle-the-march-of-the-black-queen",
    displayName: "Ogre Battle - The March of the Black Queen",
    filename: "ogre_battle_the_march_of_the_black_queen.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-paladins-quest",
    displayName: "Paladin's Quest",
    filename: "paladins_quest.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-parodius-non-sense-fantasy",
    displayName: "Parodius Non-Sense Fantasy",
    filename: "parodius_non_sense_fantasy.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-phalanx",
    displayName: "Phalanx",
    filename: "phalanx.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-pilotwings",
    displayName: "Pilotwings",
    filename: "pilotwings.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-pitfall",
    displayName: "Pitfall",
    filename: "pitfall.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-plok",
    displayName: "Plok",
    filename: "plok.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-pocky-and-rocky-1",
    displayName: "Pocky & Rocky 1",
    filename: "pocky_and_rocky_1.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-pocky-and-rocky-2",
    displayName: "Pocky & Rocky 2",
    filename: "pocky_and_rocky_2.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-pop-n-twinbee-1",
    displayName: "Pop 'n' Twinbee 1",
    filename: "pop_n_twinbee_1.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-pop-n-twinbee-2-rainbow-bell-adventure",
    displayName: "Pop 'n' Twinbee 2 - Rainbow Bell Adventure",
    filename: "pop_n_twinbee_2_rainbow_bell_adventure.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-prince-of-persia-1",
    displayName: "Prince of Persia 1",
    filename: "prince_of_persia_1.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-prince-of-persia-2-the-shadow-and-the-flame",
    displayName: "Prince of Persia 2 - The Shadow & The Flame",
    filename: "prince_of_persia_2_the_shadow_and_the_flame.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-pushover",
    displayName: "Pushover",
    filename: "pushover.smc",
    genre: "puzzle",
    favorite: false,
  },
  {
    id: "snes-r-type-iii-the-third-lightning",
    displayName: "R-Type III - The Third Lightning",
    filename: "r_type_iii_the_third_lightning.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-robotrek",
    displayName: "Robotrek",
    filename: "robotrek.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-rock-n-roll-racing",
    displayName: "Rock 'n' Roll Racing",
    filename: "rock_n_roll_racing.smc",
    genre: "racing",
    favorite: false,
  },
  {
    id: "snes-romancing-saga-3",
    displayName: "Romancing Saga 3",
    filename: "romancing_saga_3.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-samurai-showdown",
    displayName: "Samurai Showdown",
    filename: "samurai_showdown.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-secret-of-evermore",
    displayName: "Secret of Evermore",
    filename: "secret_of_evermore.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-secrets-of-mana-1",
    displayName: "Secrets of Mana 1",
    filename: "secrets_of_mana_1.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-secrets-of-mana-2",
    displayName: "Secrets of Mana 2",
    filename: "secrets_of_mana_2.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-shadowrun",
    displayName: "Shadowrun",
    filename: "shadowrun.smc",
    genre: "adventure",
    favorite: false,
  },
  {
    id: "snes-sim-city",
    displayName: "Sim City",
    filename: "sim_city.smc",
    genre: "strategy",
    favorite: false,
  },
  {
    id: "snes-sky-blazer",
    displayName: "Sky Blazer",
    filename: "sky_blazer.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-soul-blazer",
    displayName: "Soul Blazer",
    filename: "soul_blazer.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-star-ocean",
    displayName: "Star Ocean",
    filename: "star_ocean.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-starfox",
    displayName: "Starfox",
    filename: "starfox.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-street-fighter-alpha-2",
    displayName: "Street Fighter Alpha 2",
    filename: "street_fighter_alpha_2.smc",
    genre: "fighting",
    favorite: true,
  },
  {
    id: "snes-street-fighter-ii-the-new-challengers",
    displayName: "Street Fighter II - The New Challengers",
    filename: "street_fighter_ii_the_new_challengers.smc",
    genre: "fighting",
    favorite: true,
  },
  {
    id: "snes-street-fighter-ii-the-world-warrior",
    displayName: "Street Fighter II - The World Warrior",
    filename: "street_fighter_ii_the_world_warrior.smc",
    genre: "fighting",
    favorite: true,
  },
  {
    id: "snes-street-fighter-ii-turbo",
    displayName: "Street Fighter II Turbo",
    filename: "street_fighter_ii_turbo.smc",
    genre: "fighting",
    favorite: true,
  },
  {
    id: "snes-stunt-race-fx",
    displayName: "Stunt Race FX",
    filename: "stunt_race_fx.smc",
    genre: "racing",
    favorite: false,
  },
  {
    id: "snes-sunset-riders",
    displayName: "Sunset Riders",
    filename: "sunset_riders.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-bomberman-2",
    displayName: "Super Bomberman 2",
    filename: "super_bomberman_2.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-bomberman-3",
    displayName: "Super Bomberman 3",
    filename: "super_bomberman_3.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-bomberman-4",
    displayName: "Super Bomberman 4",
    filename: "super_bomberman_4.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-bomberman-5-gold-cartridge",
    displayName: "Super Bomberman 5 Gold Cartridge",
    filename: "super_bomberman_5_gold_cartridge.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-castlevania-iv",
    displayName: "Super Castlevania IV",
    filename: "super_castlevania_iv.smc",
    genre: "action",
    favorite: true,
  },
  {
    id: "snes-super-double-dragon",
    displayName: "Super Double Dragon",
    filename: "super_double_dragon.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-fire-pro-wrestling-x-premium",
    displayName: "Super Fire Pro Wrestling X Premium",
    filename: "super_fire_pro_wrestling_x_premium.smc",
    genre: "fighting",
    favorite: false,
  },
  {
    id: "snes-super-ghouls-n-ghosts",
    displayName: "Super Ghouls 'n' Ghosts",
    filename: "super_ghouls_n_ghosts.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-super-james-pond-2",
    displayName: "Super James Pond 2",
    filename: "super_james_pond_2.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-super-mario-all-stars-and-world",
    displayName: "Super Mario All Stars & World",
    filename: "super_mario_all_stars_and_world.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-super-mario-kart",
    displayName: "Super Mario Kart",
    filename: "super_mario_kart.smc",
    genre: "racing",
    favorite: true,
  },
  {
    id: "snes-super-mario-rpg",
    displayName: "Super Mario RPG",
    filename: "super_mario_rpg.smc",
    genre: "rpg",
    favorite: true,
  },
  {
    id: "snes-super-mario-world",
    displayName: "Super Mario World",
    filename: "super_mario_world.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-super-metroid",
    displayName: "Super Metroid",
    filename: "super_metroid.smc",
    genre: "action",
    favorite: true,
  },
  {
    id: "snes-super-off-road",
    displayName: "Super Off Road",
    filename: "super_off_road.smc",
    genre: "racing",
    favorite: false,
  },
  {
    id: "snes-super-punch-out",
    displayName: "Super Punch-Out!!",
    filename: "super_punch_out.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-r-type",
    displayName: "Super R-Type",
    filename: "super_r_type.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-super-smash-tv",
    displayName: "Super Smash TV",
    filename: "super_smash_tv.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-star-wars-return-of-the-jedi",
    displayName: "Super Star Wars - Return of the Jedi",
    filename: "super_star_wars_return_of_the_jedi.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-super-turrican-1",
    displayName: "Super Turrican 1",
    filename: "super_turrican_1.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-super-turrican-2",
    displayName: "Super Turrican 2",
    filename: "super_turrican_2.smc",
    genre: "platformer",
    favorite: false,
  },
  {
    id: "snes-tales-of-phantasia",
    displayName: "Tales of Phantasia",
    filename: "tales_of_phantasia.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-teenage-mutant-ninja-turtles-iv-turtles-in-time",
    displayName: "Teenage Mutant Ninja Turtles IV - Turtles in Time",
    filename: "teenage_mutant_ninja_turtles_iv_turtles_in_time.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-terranigma",
    displayName: "Terranigma",
    filename: "terranigma.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-tetris-attack",
    displayName: "Tetris Attack",
    filename: "tetris_attack.smc",
    genre: "puzzle",
    favorite: false,
  },
  {
    id: "snes-un-squadron",
    displayName: "U.N. Squadron",
    filename: "un_squadron.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-uncharted-waters-1",
    displayName: "Uncharted Waters 1",
    filename: "uncharted_waters_1.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-uncharted-waters-2-new-horizons",
    displayName: "Uncharted Waters 2 - New Horizons",
    filename: "uncharted_waters_2_new_horizons.smc",
    genre: "rpg",
    favorite: false,
  },
  {
    id: "snes-uniracers",
    displayName: "Uniracers",
    filename: "uniracers.smc",
    genre: "racing",
    favorite: false,
  },
  {
    id: "snes-wild-guns",
    displayName: "Wild Guns",
    filename: "wild_guns.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-wolfenstein-3d",
    displayName: "Wolfenstein 3D",
    filename: "wolfenstein_3d.smc",
    genre: "shooter",
    favorite: false,
  },
  {
    id: "snes-wolverine-adamantium-rage",
    displayName: "Wolverine - Adamantium Rage",
    filename: "wolverine_adamantium_rage.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-yoshis-island",
    displayName: "Yoshi's Island",
    filename: "yoshis_island.smc",
    genre: "platformer",
    favorite: true,
  },
  {
    id: "snes-ys-3-wanderers-from-ys",
    displayName: "Ys 3 - Wanderers from Ys",
    filename: "ys_3_wanderers_from_ys.smc",
    genre: "action",
    favorite: false,
  },
  {
    id: "snes-zelda-a-link-to-the-past",
    displayName: "Zelda - A Link to the Past",
    filename: "zelda_a_link_to_the_past.smc",
    genre: "adventure",
    favorite: true,
  },
  {
    id: "snes-zombies-ate-my-neighbors",
    displayName: "Zombies Ate My Neighbors",
    filename: "zombies_ate_my_neighbors.smc",
    genre: "action",
    favorite: false,
  },
];
