/**
 * Writes src/__tests__/fixtures/new-saves.json: the saves that the store
 * code of this checkout writes (src/__tests__/new-save-scenarios.ts).
 * rollback.sh runs it, then loads the saves with the old store code
 * (rollback.test.ts).
 */
import { vi } from "vitest";

vi.hoisted(() => {
  vi.useFakeTimers({ toFake: ["Date"] });
  vi.setSystemTime(new Date(Date.UTC(2026, 9, 3, 12, 0, 0)));
  let seed = 20261003;
  Math.random = () => {
    seed = (seed * 1664525 + 1013904223) % 4294967296;
    return seed / 4294967296;
  };
});

import { it } from "vitest";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { writeNewSaves } from "@/__tests__/new-save-scenarios";

it("writes the saves of the new store code", async () => {
  const saves = await writeNewSaves();
  const out = join(__dirname, "../../src/__tests__/fixtures/new-saves.json");
  writeFileSync(
    out,
    JSON.stringify(
      {
        note: "Generated by apps/web/scripts/legacy-saves/rollback.sh from the store code of this checkout. Do not edit by hand.",
        saves,
      },
      null,
      2
    ) + "\n"
  );
});
