/**
 * The master side of the no-worse-than-master proof: no-worse.sh unpacks
 * the src of master and runs this file against it. It makes the inputs with
 * master's stores, runs every cell of src/__tests__/no-worse/harness.ts with
 * master's useAuthSync and stores, and writes
 * src/__tests__/fixtures/no-worse-master.json for
 * src/__tests__/no-worse-than-master.test.tsx.
 */
import { vi } from "vitest";

vi.hoisted(() => {
  vi.useFakeTimers({ toFake: ["setTimeout", "clearTimeout", "setInterval", "clearInterval", "Date"] });
  vi.setSystemTime(new Date("2026-10-20T13:00:00Z"));
  // Seeded Math.random (ids, boards), so two runs make the same inputs.
  let seed = 20261020;
  Math.random = () => {
    seed = (seed * 1664525 + 1013904223) % 4294967296;
    return seed / 4294967296;
  };
});

const session = vi.hoisted(() => ({
  current: { data: null as null | { user: { id: string } }, status: "unauthenticated" as string },
}));
vi.mock("next-auth/react", () => ({
  useSession: () => session.current,
  signOut: vi.fn(async () => undefined),
  signIn: vi.fn(async () => undefined),
  SessionProvider: ({ children }: { children: unknown }) => children,
}));

import { afterAll, afterEach, beforeAll, beforeEach, it } from "vitest";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  afterCell,
  allCells,
  beforeCell,
  createContext,
  harnessHash,
  makeInputs,
  type CellResult,
  type Inputs,
} from "../../src/__tests__/no-worse/harness";

const ctx = createContext(session);
const cells = allCells();
const results: Record<string, CellResult | { error: string }> = {};
let inputs: Inputs = {};

beforeAll(async () => {
  vi.spyOn(console, "error").mockImplementation(() => {});
  vi.spyOn(console, "warn").mockImplementation(() => {});
  inputs = await makeInputs();
  vi.restoreAllMocks();
});
beforeEach(() => beforeCell(ctx));
afterEach(() => afterCell());

afterAll(() => {
  const out = join(__dirname, "../../src/__tests__/fixtures/no-worse-master.json");
  writeFileSync(
    out,
    JSON.stringify(
      {
        note: "Generated by apps/web/scripts/legacy-saves/no-worse.sh: the inputs and the losses of every cell with master's code. Do not edit by hand.",
        commit: process.env.LEGACY_COMMIT ?? "working tree",
        harness: harnessHash(),
        inputs,
        results,
      },
      null,
      1
    ) + "\n"
  );
});

it.each(cells.map((cell) => [cell.id, cell] as const))("master: %s", async (id, cell) => {
  try {
    results[id] = await cell.run(ctx, inputs[cell.appId]);
  } catch (error) {
    results[id] = { error: String(error).slice(0, 300) };
  }
});
