/**
 * Clips runtime: main-thread capture machinery (plan 4.1, 6.2, 7, 5).
 * Nothing here reads window or navigator at import time.
 */
export {
  installRafDispatcher,
  hasRafDispatcher,
  isRealmDead,
  type FrameHook,
  type InstallOptions,
  type RafDispatcher,
  type RafRealm,
} from "./rafDispatcher";
export {
  estimateDisplayHz,
  estimateVsyncMs,
  forgetDisplayRates,
  inferLowPowerMode,
  measureDisplayHz,
  measureDisplayRate,
  measureRafIntervals,
  rememberDisplayHz,
  rememberedDisplayHz,
  rungTable,
  screenKey,
  snapHz,
  strideFor,
  LOW_POWER_MIN_INTERVALS,
  LOW_POWER_SHORTEST_MS,
  MIN_VSYNC_CLUSTER,
  RUNG_FLOOR_FPS,
  STANDARD_RATES,
  VSYNC_CLUSTER_SPAN,
  type DisplayRate,
  type Rung,
} from "./rungs";
export {
  FramePump,
  type CapturedPayload,
  type CaptureTicket,
  type FramePumpOptions,
  type FramePumpStats,
  type FrameSink,
} from "./framePump";
export {
  buildLadder,
  Governor,
  governorInputs,
  CLEAN_WINDOWS_TO_STEP_UP,
  LOW_POWER_KEEP_SECONDS,
  MAX_CAPTURE_SHARE,
  MAX_FPS_LOSS,
  MAX_READBACK_BUSY,
  MAX_READBACK_LATENCY_FRAMES,
  MAX_STEP_UPS,
  SEVERE_FPS_LOSS,
  VIOLATIONS_TO_STEP_DOWN,
  WINDOW_MS,
  type CaptureSample,
  type GovernorDecision,
  type GovernorLevel,
  type GovernorOptions,
  type LevelKind,
  type PowerState,
  type PressureState,
  type ViolationReason,
  type WindowReport,
} from "./governor";
export { avcCodecString, avcLevelHex, profileOfCodec, PROFILE_ORDER, type AvcProfile } from "./avcLevel";
export {
  AAC_PROBE_SAMPLES,
  DEFAULT_TARGETS,
  isDefinitiveReport,
  runProbe,
  SOFTWARE_TARGET,
  TRANSIENT_REASONS,
  type ProbeEnv,
  type ProbeRequest,
  type ProbeResponse,
  type VideoAttempt,
  type VideoTarget,
  type WorkerProbeReport,
} from "./capabilityProbe";
export {
  bitrateFor,
  chooseVideoEncoder,
  memoryClassFor,
  probeCapabilities,
  probeCapabilityReport,
  probeWebGL2Readback,
  quickProbes,
  resetProbeSession,
  selectTier,
  CAPS_CACHE_ITEM,
  CACHE_MAX_AGE_MS,
  SOFTWARE_PRESETS,
  type CapabilityReport,
  type ContentKind,
  type EncoderPlan,
  type MemoryInput,
  type ProbeGlobals,
  type ProbeOptions,
  type TierInput,
  type WorkerLike,
} from "./capabilities";
