/** Exact legacy names, without importing any game modules. */
export const PROGRESS_STORAGE_KEYS: Readonly<Record<string, string>> = Object.freeze({
  "2048": "2048-game-state",
  "arkanoid": "arkanoid-state",
  "asteroids": "asteroids-game-state",
  "blitz-bomber": "blitz-bomber-progress",
  "bomberman": "bomberman-state",
  "breakout": "breakout-game-state",
  "checkers": "checkers-progress",
  "chess": "hank-chess-state",
  "cookie-clicker": "cookie-clicker-storage",
  "dino-runner": "dino-runner-progress",
  "endless-runner": "endless-runner-storage",
  "flappy-bird": "flappy-bird-progress",
  "four-wheeler-3d": "four-wheeler-3d-game-state",
  "hextris": "hextris-game-state",
  "hill-climb": "hill-climb-storage",
  "math-attack": "math-attack-progress",
  "memory-match": "memory-match-progress",
  "monster-truck": "monster-truck-save",
  "oregon-trail": "oregon-trail-storage",
  "platformer": "hank-platformer-progress",
  "quoridor": "quoridor-progress",
  "retro-arcade": "retro-arcade-progress",
  "snake": "snake-game-state",
  "space-invaders": "space-invaders-progress",
  "wordle": "wordle-progress",
  "drawing-app": "drawing-app-progress",
  "drum-machine": "drum-machine-state",
  "joke-generator": "joke-generator-progress",
  "toy-finder": "toy-finder-progress",
  "trivia": "trivia-progress",
  "virtual-pet": "virtual-pet-state",
  "weather": "weather-app-progress",
  "achievements": "achievements-progress"
});
